### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-phpunit-result-printer#140]
- [x] webignition/basil-runner-documents#13
- [x] webignition/yaml-document-generator#7
- [x] webignition/yaml-document-set-parser#9
